### ISSUE TITLE
Mod compatibility issues

### ISSUE THREAD

**Issue by Derpumu** [Derpumu/Pacifist#1]
Known mods with compatibility problems:
~~[500 bot start](https://github.com/Derpumu/Pacifist/issues/2)~~ (fixed)
~~[IndustrialRevolution3](https://github.com/Derpumu/Pacifist/issues/13)~~ (won't fix, IR3 has its own peaceful mode)
~~[Krastorio2](https://github.com/Derpumu/Pacifist/issues/12)~~ (fixed)
~~[pypostporcessing](https://github.com/Derpumu/Pacifist/issues/10)~~ (fixed)

Following modpacks/overhaul mods are affected:
- Angel's mods
- Freightforwarding
- ~~Krastorio~~
- ~~Pyanodon's~~
- Seablock

Mods yet to be checked for compatibility:
~~- https://mods.factorio.com/mod/Power%20Armor%20MK3~~

**Comment by Hargrive-Rush** [comment]
Make aai-industry compitable please. I always long time looking mod like this, this is beautiful mod.

**Comment by Derpumu** [comment]
Already on it, will come with the next release

**Comment by Hargrive-Rush** [comment]
Thanks a lot!

**Comment by arnemertz** [comment]
aai-industry should be compatible now.

**Comment by Derpumu** [comment]
aai-industry is compatible now

**Comment by Hargrive-Rush** [comment]
Ooooo, im very happy now! Thank you!

**Comment by Derpumu** [comment]
remaining compatibility checks are done in individual tickets
