### ISSUE TITLE
Remove or mask weapon/ammo slots

### ISSUE THREAD

**Issue by dperelman** [Derpumu/Pacifist#51]
The weapon/ammo slots are unusable with this mod, but they still show up in the UI. It looks like the modding UI doesn't allow removing them ([1](https://old.reddit.com/r/factorio/comments/h9sfgn/help_removehide_gun_slots_with_a_mod/) [2](https://forums.factorio.com/viewtopic.php?t=32869)), but I was wondering if it might allow changing the gun/ammo icon used there to something else to indicate those slots are disabled.

(I think the other way to get this implemented would be to make a feature request, which I [just posted](https://forums.factorio.com/viewtopic.php?f=6&t=112719) on the Factorio forums.)

**Comment by Derpumu** [comment]
Thanks for the suggestion. I wouldn't completely trove them as some mods provide "weapons" that actually are tools, and Pacifist has exceptions to leave them in the game. Examples are the nanobots and grappling guns and their ammo. I'll do some research whether the icons for empty slots can be changed, but I'll have to confess that it's not a top priority, so unless I find some easy solution quickly, it won't happen for some time.

**Comment by dperelman** [comment]
Thanks. After a quick look, it looks like https://lua-api.factorio.com/latest/prototypes/UtilitySprites.html#slot_icon_ammo and https://lua-api.factorio.com/latest/prototypes/UtilitySprites.html#slot_icon_gun sound like those icons.

I may try to figure it out myself and make a PR.
